module.exports = {
  'SLACK_CLIENT_ID': process.env.SLACK_CLIENT_ID || 'YOUR_SLACK_CLIENT_ID',
  'SLACK_SECRET': process.env.SLACK_SECRET || 'YOUR_SLACK_SECRET',
  'VERIFICATION_TOKEN': process.env.VERIFICATION_TOKEN || 'YOUR_VERIFICATION_TOKEN',
  'API_KEY': process.env.API_KEY || 'YOUR_TRUSTPILOT_API_KEY',
  'API_SECRET': process.env.API_SECRET || 'YOUR_TRUSTPILOT_API_SECRET',
  'API_HOST': process.env.API_HOST || 'https://api.trustpilot.com',
  'BUSINESS_USER_NAME': process.env.BUSINESS_USER_NAME || 'YOUR_TRUSTPILOT_BUSINESS_USER_NAME',
  'BUSINESS_USER_PASS': process.env.BUSINESS_USER_PASS || 'YOUR_TRUSTPILOT_BUSINESS_USER_PASS',
  'BUSINESS_UNIT_ID': process.env.BUSINESS_UNIT_ID || 'YOUR_TRUSTPILOT_BUSINESS_UNIT_ID',
};
